version: "3"
services:
    redis:
        image: redis
        restart: unless-stopped
        container_name: "redis"
        network_mode: "host"
    postgres:
        image: postgres
        shm_size: 128mb
        restart: unless-stopped
        container_name: "postgres"
        environment:
            - POSTGRES_PASSWORD=postgres
        network_mode: "host"
    mercurjs_backend:
        image: local/mercurjs_backend
        restart: unless-stopped
        container_name: "mercurjs_backend"
        network_mode: "host"
    mercurjs_storefront:
        image: local/mercurjs_storefront
        restart: unless-stopped
        container_name: "mercurjs_storefront"
        network_mode: "host"
    mercurjs_web:
        image: local/mercurjs_web
        restart: unless-stopped
        container_name: "mercurjs_web"
        network_mode: "host"

