version: "3"
services:
    mercurjs_backend:
        image: local/mercurjs_backend
        restart: unless-stopped
        container_name: "mercurjs_backend"
        network_mode: "host"
    mercurjs_storefront:
        image: local/mercurjs_storefront
        restart: unless-stopped
        container_name: "mercurjs_storefront"
        network_mode: "host"
    mercurjs_web:
        image: local/mercurjs_web
        restart: unless-stopped
        container_name: "mercurjs_web"
        network_mode: "host"
        volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/:ro

