#!/bin/bash

# docker run -d \
#            --name mercurjs \
#            --restart unless-stopped \
#            --network host \
#            local/mercurjs

docker run -d \
           --name web \
           --restart unless-stopped \
           --network acs_genieacs_network \
           -p 80:80 -p 443:443 \
           -v /etc/letsencrypt/:/etc/letsencrypt/ \
           local/httpd

