#!/bin/bash

# docker run -d \
#            --name mercurjs_backend \
#            --restart unless-stopped \
#            --network host \
#            local/mercurjs_backend

# docker run -d \
#            --name mercurjs_storefront \
#            --restart unless-stopped \
#            --network host \
#            local/mercurjs_storefront

docker run -d \
           --name mercurjs_apache \
           --restart unless-stopped \
           --network host \
           local/mercurjs_apache

# -v /etc/letsencrypt/:/etc/letsencrypt/ \
