#!/bin/bash

if [ ! -d /root/workspace/mercur ]; then
    cd /root/workspace && npx mercur-cli install
    # Disable localhost binding for admin and vendor panels
    cd /root/workspace/mercur/admin-panel/ && sed -i 's/open: true,/open: true,\n      host: true,/' vite.config.mts
    cd /root/workspace/mercur/vendor-panel/ && sed -i 's/open: true,/open: true,\n      host: true,/' vite.config.mts
fi

cd /root/workspace/mercur && /root/workspace/node_modules/.bin/mercur-cli dev

